> ### **Assignment 2 - Numpy Array Operations** 



# Numpy Array Functions


### Demonstration of different numpy arrays manipulators

On the cells bellow there will be explanation and demonstrations by examples of the following numpy functions:

- np.append
- np.delete
- np.split
- ndarray.T
- np.insert

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
import numpy as np

# List of functions explained 
function1 = np.append 

function2 = np.delete

function3 = np.split

function4 = ndarray.T

function5 = np.insert

## Function 1 - np.append

Inserts a new value at the end of the choose array.

In [2]:
# Example 1 - working 
arr1 = np.array([[1,2,3],[1,2,3]])
arr2 = np.array([[4,5],[4,5]])

np.append(arr1, arr2, axis = 1)

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

np.append inserts new values at the end of an existing array.

In [3]:
# Example 2 - working
arr1 = np.array([[1,2,3],[1,2,3]])

np.append((arr1),([[4,5],[4,5]]), axis = 1)

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

Same as before, but the values to be "added" are directly inserted into the np.append function, without the need of creating a new array.

In [4]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.append((arr1, arr2), axis=0) #the arrays have a diffent dimension from each other.

TypeError: _append_dispatcher() missing 1 required positional argument: 'values'

## Function 2 - np.delete

Deletes an axis of a given array and returns a new one. 
`np.delete(array, object, axis)`

In [5]:
# Example 1 - working
arr1 = np.array([[1,2,3],[1,2,3]])
arr2 = np.array([1,2])

np.delete(arr1, arr2, axis = 1)

array([[1],
       [1]])

It deletes values from an array given it's index.

In [6]:
# Example 2 - working
arr1 = np.array([[1,2,3],[1,2,3]])
np.delete(arr1, ([2]), axis = 1)

array([[1, 2],
       [1, 2]])

Passing the index of the value to be deleted directly into the `np.delete` function.

In [7]:
# Example 3 - breaking (to illustrate when it breaks)
# Example 1 - working
arr1 = np.array([[1,2,3],[1,2,3]])
arr2 = np.array([[1],[3]])

np.delete(arr1, arr2, axis = 1)

IndexError: index 3 is out of bounds for axis 0 with size 3

There is no value at index 3. The index given to be deleted must be into the arrays size limit.

## Function 3 - np.split

Splits a array into a given number of multiple arrays, possibly of the same size.
`np.split(array, indices)`

In [8]:
# Example 1 - working
arr1 = np.array([1,2,3,4,5,6,7,8])

np.split(arr1, 4)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

Using `np.split` in the arr1 (of size 8) slpits it into 4 equal parts.

In [9]:
# Example 2 - working
arr1 = np.array([[1,2,3,4],[1,2,3,4]])

np.split(arr1, 2)

[array([[1, 2, 3, 4]]), array([[1, 2, 3, 4]])]

Splited the arr1 into two one dimension sub-arrays.

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([[1,2,3,4],[1,2,3,4]])

np.split(arr1, 3)

ValueError: array split does not result in an equal division

The array arr1 only has two dimensions. The split function cannot pass the arrays boundaries, so it can give a equal division.

## Function 4 - ndarray.T

Transpose a given array, or multiple arrays.
`ndarray.T`

In [11]:
# Example 1 - working
arr = np.array([[1,2,3,4], [3,4,5,6]])
print("transposed:", arr.T)

transposed: [[1 3]
 [2 4]
 [3 5]
 [4 6]]


Generates a matriz through the ordered exchange of rows by columns.

In [12]:
# Example 2 - working
arr = np.array([1.,2.,3.,4.])
print("Before transposing:", arr)
transposed_arr = arr.T
print("After transposing:", transposed_arr)

Before transposing: [1. 2. 3. 4.]
After transposing: [1. 2. 3. 4.]


The second array only has one dimension, therefor cannot be transposed into itself.

In [13]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array([[1,2,3,4]], [[3,4,5,6]])
print("transposed:", arr.T)

TypeError: Field elements must be 2- or 3-tuples, got '[3, 4, 5, 6]'

Matrices dimensions are invalid to be transposed. (?)

## Function 5 - np.insert

Inserts a new value at the beginning of an array.

In [14]:
# Example 1 - working
arr = np.array([[1,2,3],[1,2,3]])
print("Inserting the values 4 and 5:", np.insert(arr,1,5, axis=1))

Inserting the values 4 and 5: [[1 5 2 3]
 [1 5 2 3]]


In [15]:
# Example 2 - working
arr = np.array([1, 2, 3])
print(np.insert(arr,1,5))

[1 5 2 3]


Inserting values into a one dimension array.

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array([[1,2,3],[1,2,3]])
print(np.insert(arr,4,5, axis=2))

AxisError: axis 2 is out of bounds for array of dimension 2

The axis argument is incompatible with the matrix dimension.

## Conclusion

In this nootebook we saw a few array manipulation functions, exploring it's differents uses, and getting used to the fact that they may break quite easily.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Numpy array functions: https://www.educba.com/numpy-array-functions/
* Explanation of transposed matrices: https://matematicabasica.net/matriz-transposta/
* Array manipulation routines: https://numpy.org/doc/stable/reference/routines.array-manipulation.html

In [18]:
# Install the library
!pip install jovian --upgrade --quiet

In [19]:
# Import it
import jovian

<IPython.core.display.Javascript object>

In [ ]:
# Capture and upload a snapshot
jovian.commit(project='assignment2-numpy-array-operations')

<IPython.core.display.Javascript object>